import { CategoriesPageModel } from "src/app/shared/models/categories-page.model";

export const CATEGORIES: CategoriesPageModel[] = [
	{
		iconDark: 'assets/img/categorias/ia-dark.png',
		iconLight: 'assets/img/categorias/ia-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-ia',
		class: 'drop box',
		linkCategory: '/blog/ia',
		state: 'active',
		nameCategorie: 'ai',
		posicion: 'rot-2',
		colorFondo: 'bg-Ai',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/android.png',
		iconLight: 'assets/img/categorias/android.png',
		height: '60',
		width: 'auto',
		alt: 'icon-android',
		class: 'drop box',
		linkCategory: '/blog/android',
		state: 'inactive',
		nameCategorie: 'android',
		posicion: 'pos-z',
		colorFondo: 'bg-Android',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/angular.png',
		iconLight: 'assets/img/categorias/angular.png',
		height: '50',
		width: 'auto',
		alt: 'icon-angular',
		class: 'drop box',
		linkCategory: '/blog/angular',
		state: 'active',
		nameCategorie: 'angular',
		posicion: 'rot-2',
		colorFondo: 'bg-Angular',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/css-dark.png',
		iconLight: 'assets/img/categorias/css-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-css',
		class: 'drop box',
		linkCategory: '/blog/css',
		state: 'active',
		nameCategorie: 'css',
		posicion: 'pos-z',
		colorFondo: 'bg-Css',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/dart-dark.png',
		iconLight: 'assets/img/categorias/dart-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-dart',
		class: 'drop box',
		linkCategory: '/blog/dart',
		state: 'inactive',
		nameCategorie: 'dart',
		posicion: 'rot-2',
		colorFondo: 'bg-Dart',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/sql.png',
		iconLight: 'assets/img/categorias/sql.png',
		height: '60',
		width: 'auto',
		alt: 'icon-db',
		class: 'drop box',
		linkCategory: '/blog/db',
		state: 'inactive',
		nameCategorie: 'db',
		posicion: 'rot-2',
		colorFondo: 'bg-Sql',
		color: 'text-dark'
	},
	{
		iconDark: 'assets/img/categorias/developer.png',
		iconLight: 'assets/img/categorias/developer.png',
		height: '60',
		width: 'auto',
		alt: 'icon-developer',
		class: 'drop box',
		linkCategory: '/blog/developer',
		state: 'active',
		nameCategorie: 'developer',
		posicion: 'rot-2',
		colorFondo: 'bg-Developer',
		color: 'text-dark'
	},
	{
		iconDark: 'assets/img/categorias/electron-dark.png',
		iconLight: 'assets/img/categorias/electron-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-electron',
		class: 'drop box',
		linkCategory: '/blog/electron',
		state: 'inactive',
		nameCategorie: 'electron',
		posicion: 'pos-z',
		colorFondo: 'bg-Electron',
		color: 'text-dark'
	},
	{
		iconDark: 'assets/img/categorias/flutter-dark.png',
		iconLight: 'assets/img/categorias/flutter-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-flutter',
		class: 'drop box',
		linkCategory: '/blog/flutter',
		state: 'inactive',
		nameCategorie: 'flutter',
		posicion: 'rot-1',
		colorFondo: 'bg-Flutter',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/git-dark.png',
		iconLight: 'assets/img/categorias/git-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-git',
		class: 'drop box',
		linkCategory: '/blog/git',
		state: 'inactive',
		nameCategorie: 'git',
		posicion: 'rot-3',
		colorFondo: 'bg-Git',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/html-dark.png',
		iconLight: 'assets/img/categorias/html-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-html',
		class: 'drop box',
		linkCategory: '/blog/html',
		state: 'inactive',
		nameCategorie: 'html',
		posicion: 'pos-z',
		colorFondo: 'bg-Html',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/logo-java.png',
		iconLight: 'assets/img/categorias/logo-java.png',
		height: '60',
		width: 'auto',
		alt: 'icon-java',
		class: 'drop box',
		linkCategory: '/blog/java',
		state: 'inactive',
		nameCategorie: 'java',
		posicion: 'rot-2',
		colorFondo: 'bg-Java',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/javascript.png',
		iconLight: 'assets/img/categorias/javascript.png',
		height: '60',
		width: 'auto',
		alt: 'icon-javascript',
		class: 'drop box',
		linkCategory: '/blog/javascript',
		state: 'active',
		nameCategorie: 'javascript',
		posicion: 'rot-2',
		colorFondo: 'bg-Javascript',
		color: 'text-dark'
	},
	{
		iconDark: 'assets/img/categorias/kotlin-dark.png',
		iconLight: 'assets/img/categorias/kotlin-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-kotlin',
		class: 'drop box',
		linkCategory: '/blog/kotlin',
		state: 'inactive',
		nameCategorie: 'kotlin',
		posicion: 'pos-z',
		colorFondo: 'bg-Kotlin',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/linux-dark.png',
		iconLight: 'assets/img/categorias/linux-white.png',
		height: '40',
		width: 'auto',
		alt: 'icon-linux',
		class: 'drop box',
		linkCategory: '/blog/linux',
		state: 'active',
		nameCategorie: 'linux',
		posicion: 'rot-2',
		colorFondo: 'bg-Linux',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/typescript-dark.png',
		iconLight: 'assets/img/categorias/typescript-white.png',
		height: '40',
		width: 'auto',
		alt: 'icon-typescript',
		class: 'drop box',
		linkCategory: '/blog/typescript',
		state: 'active',
		nameCategorie: 'typescript',
		posicion: 'rot-2',
		colorFondo: 'bg-Typescript',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/web-dark.png',
		iconLight: 'assets/img/categorias/web-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-web',
		class: 'drop box',
		linkCategory: '/blog/web',
		state: 'active',
		nameCategorie: 'web',
		posicion: 'rot-2',
		colorFondo: 'bg-Web',
		color: 'text-light'
	},
	{
		iconDark: 'assets/img/categorias/windows-dark.png',
		iconLight: 'assets/img/categorias/windows-white.png',
		height: '60',
		width: 'auto',
		alt: 'icon-windows',
		class: 'drop box',
		linkCategory: '/blog/windows',
		state: 'active',
		nameCategorie: 'windows',
		posicion: 'rot-2',
		colorFondo: 'bg-Windows',
		color: 'text-light'
	}
]