import { TopTecnologyModel } from "../models/top-tecnology.model";

export const TOP_DATABASES:TopTecnologyModel[] = [
    {
        name:'PostgreSQL',
        value:'48.7'
    },
    {
        name:'MySQL',
        value:'40.3'
    },
    {
        name:'SQLite',
        value:'33.1'
    },
    {
        name:'Microsoft SQL Server',
        value:'25.3'
    },
    {
        name:'MongoDB',
        value:'24.8'
    },
    {
        name:'Redis',
        value:'20'
    },
    {
        name:'MariaDB',
        value:'17.2'
    },
    {
        name:'Elascticsearch',
        value:'12.5'
    },
    {
        name:'Oracle',
        value:'10.1'
    },
    {
        name:'DynanoDB',
        value:'7.9'
    },
    {
        name:'Firebase Realtime Database',
        value:'5.8'
    },
    {
        name:'Cloud Firestore',
        value:'5.4'
    },
    {
        name:'BigQuery',
        value:'4.8'
    },
    {
        name:'Microsoft Access',
        value:'4.2'
    },
    {
        name:'Supabase',
        value:'4'
    },
    {
        name:'H2',
        value:'3.8'
    },
    {
        name:'CosmosDB',
        value:'3.3'
    },
    {
        name:'Snowflake',
        value:'2.6'
    },
    {
        name:'InfluxDB',
        value:'2.5'
    },
    {
        name:'Cassandra',
        value:'2.4'
    },
    {
        name:'Databricks SQL',
        value:'1.9'
    },
    {
        name:'Neo4j',
        value:'1.9'
    },
    {
        name:'IBM DB2',
        value:'1.7'
    },
    {
        name:'ClickHouse',
        value:'1.7'
    },
    {
        name:'Solr',
        value:'1.5'
    },
    {
        name:'DuckDB',
        value:'1.4'
    },
    {
        name:'Firebird',
        value:'1.1'
    },
    {
        name:'Couch DB',
        value:'1'
    },
    {
        name:'CockroachDB',
        value:'1'
    },
    {
        name:'Couchbase',
        value:'0.7'
    },
    {
        name:'Presto',
        value:'0.6'
    },
    {
        name:'Datomic',
        value:'0.4'
    },
    {
        name:'Event Store DB',
        value:'0.3'
    },
    {
        name:'RavenDB',
        value:'0.3'
    },
    {
        name:'TiDB',
        value:'0.2'
    }
]