import { TopTecnologyModel } from "../models/top-tecnology.model";

export const TOP_FRAMEWORKS:TopTecnologyModel[] = [
    {
        name:'Node.js',
        value:'40.8'
    },
    {
        name:'React',
        value:'39.5'
    },
    {
        name:'JQuery',
        value:'21.4'
    },
    {
        name:'Next.js',
        value:'17.9'
    },
    {
        name:'Express',
        value:'17.8'
    },
    {
        name:'Angular',
        value:'17.1'
    },
    {
        name:'ASP.NET CORE',
        value:'16.9'
    },
    {
        name:'Vue.js',
        value:'15.4'
    },
    {
        name:'ASP.NET',
        value:'12.9'
    },
    {
        name:'Flash',
        value:'12.9'
    },
    {
        name:'Spring Boot',
        value:'12.7'
    },
    {
        name:'Django',
        value:'12'
    },
    {
        name:'Wordpress',
        value:'11.8'
    },
    {
        name:'FastAPI',
        value:'9.9'
    },
    {
        name:'Laravel',
        value:'7.9'
    },
    {
        name:'AngularJS',
        value:'6.8'
    },
    {
        name:'Svelte',
        value:'6.5'
    },
    {
        name:'NestJS',
        value:'5.8'
    },
    {
        name:'Blazor',
        value:'4.9'
    },
    {
        name:'Ruby on Rails',
        value:'4.7'
    },
    {
        name:'Nuxt.js',
        value:'3.6'
    },
    {
        name:'Htmx',
        value:'3.3'
    },
    {
        name:'Symfony',
        value:'3.2'
    },
    {
        name:'Astro',
        value:'3'
    },
    {
        name:'Fastify',
        value:'2.2'
    },
    {
        name:'Deno',
        value:'1.9'
    },
    {
        name:'Phoenix',
        value:'1.9'
    },
    {
        name:'Drupal',
        value:'1.9'
    },
    {
        name:'Strapi',
        value:'1.7'
    },
    {
        name:'Codelgniter',
        value:'1.7'
    },
    {
        name:'Gatsby',
        value:'1.6'
    },
    {
        name:'Remix',
        value:'1.6'
    },
    {
        name:'Solid.js',
        value:'1.2'
    },
    {
        name:'Yii 2',
        value:'0.9'
    },
    {
        name:'Play Framework',
        value:'0.8'
    },
    {
        name:'Elm',
        value:'0.6'
    },
]