import { TopTecnologyModel } from "../models/top-tecnology.model";

export const TOP_FRAMEWORKS:TopTecnologyModel[] = [
    {
        name:'Node.js',
        value:'48.7'
    },
    {
        name:'React',
        value:'44.7'
    },
    {
        name:'JQuery',
        value:'23.4'
    },
    {
        name:'Next.js',
        value:'20.8'
    },
    {
        name:'Express',
        value:'19.9'
    },
    {
        name:'ASP.NET CORE',
        value:'19.7'
    },
    {
        name:'Angular',
        value:'18.2'
    },
    {
        name:'Vue.js',
        value:'17.6'
    },
    {
        name:'FastAPI',
        value:'14.8'
    },
    {
        name:'Spring Boot',
        value:'14.7'
    },
    {
        name:'Flash',
        value:'14.4'
    },
    {
        name:'ASP.NET',
        value:'14.2'
    },
    {
        name:'Wordpress',
        value:'13.6'
    },
    {
        name:'Django',
        value:'12.6'
    },
    {
        name:'Laravel',
        value:'8.9'
    },
    {
        name:'AngularJS',
        value:'7.2'
    },
    {
        name:'Svelte',
        value:'7.2'
    },
    {
        name:'Blazor',
        value:'7'
    },
    {
        name:'NestJS',
        value:'5.8'
    },
    {
        name:'Ruby on Rails',
        value:'4.7'
    },
    {
        name:'Nuxt.js',
        value:'3.6'
    },
    {
        name:'Htmx',
        value:'3.3'
    },
    {
        name:'Symfony',
        value:'3.2'
    },
    {
        name:'Astro',
        value:'3'
    },
    {
        name:'Fastify',
        value:'2.2'
    },
    {
        name:'Deno',
        value:'1.9'
    },
    {
        name:'Phoenix',
        value:'1.9'
    },
    {
        name:'Drupal',
        value:'1.9'
    },
    {
        name:'Strapi',
        value:'1.7'
    },
    {
        name:'Codelgniter',
        value:'1.7'
    },
    {
        name:'Gatsby',
        value:'1.6'
    },
    {
        name:'Remix',
        value:'1.6'
    },
    {
        name:'Solid.js',
        value:'1.2'
    },
    {
        name:'Yii 2',
        value:'0.9'
    },
    {
        name:'Play Framework',
        value:'0.8'
    },
    {
        name:'Elm',
        value:'0.6'
    },
]