import { TopTecnologyModel } from "../models/top-tecnology.model";

export const TOP_IDES:TopTecnologyModel[] = [
    {
        name:'Visual Studio Code',
        value:'73.6'
    },
    {
        name:'Visual Studio',
        value:'29.3'
    },
    {
        name:'IntelliJ IDEA',
        value:'26.8'
    },
    {
        name:'Notepad++',
        value:'23.9'
    },
    {
        name:'Vim',
        value:'21.6'
    },
    {
        name:'Android Studio',
        value:'16.1'
    },
    {
        name:'PyCharm',
        value:'15.1'
    },
    {
        name:'Jupyter Notebook/ JupyterLab',
        value:'12.8'
    },
    {
        name:'NeoVim',
        value:'12.5'
    },
    {
        name:'Sublime Text',
        value:'10.9'
    },
    {
        name:'Eclipse',
        value:'9.4'
    },
    {
        name:'Xcode',
        value:'9.3'
    },
    {
        name:'Nano',
        value:'9.2'
    },
    {
        name:'WebStorm',
        value:'7.5'
    },
    {
        name:'PhpStorm',
        value:'5.9'
    },
    {
        name:'Rider',
        value:'5.7'
    },
    {
        name:'DataGrip',
        value:'5.1'
    },
    {
        name:'VSCodium',
        value:'4.8'
    },
    {
        name:'IPython',
        value:'4.7'
    },
    {
        name:'CLion',
        value:'4.6'
    },
    {
        name:'Emacs',
        value:'4.2'
    },
    {
        name:'Goland',
        value:'3.3'
    },
    {
        name:'NeatBeans',
        value:'2.9'
    },
    {
        name:'RStudio',
        value:'2.8'
    },
    {
        name:'Qt Creator',
        value:'2.7'
    },
    {
        name:'Code::Blocks',
        value:'2.1'
    },
    {
        name:'Kate',
        value:'1.8'
    },
    {
        name:'Fleet',
        value:'1.7'
    },
    {
        name:'Helix',
        value:'1.7'
    },
    {
        name:'Spyder',
        value:'1.4'
    },
    {
        name:'RubyMine',
        value:'1.1'
    },
    {
        name:'Geany',
        value:'1'
    },
    {
        name:'Rad Studio',
        value:'1'
    },
    {
        name:'BBEdit',
        value:'0.9'
    },
    {
        name:'Spacemacs',
        value:'0.4'
    },
]