import { TopTecnologyModel } from "../models/top-tecnology.model";

export const TOP_LANGUAGE:TopTecnologyModel[] = [
    {
        name:'JS',
        value:'62.3'
    },
    {
        name:'HTML/CSS',
        value:'52.9'
    },
    {
        name:'PY',
        value:'51'
    },
    {
        name:'SQL',
        value:'51'
    },
    {
        name:'TS',
        value:'38.5'
    },
    {
        name:'Bash/Shell',
        value:'33.9'
    },
    {
        name:'Java',
        value:'30.3'
    },
    {
        name:'C#',
        value:'27.1'
    },
    {
        name:'C++',
        value:'23'
    },
    {
        name:'C',
        value:'20.3'
    },
    {
        name:'PHP',
        value:'18.2'
    },
    {
        name:'PowerShell',
        value:'13.8'
    },
    {
        name:'Go',
        value:'13.5'
    },
    {
        name:'Rust',
        value:'12.6'
    },
    {
        name:'Kotlin',
        value:'9.4'
    },
    {
        name:'Lua',
        value:'6.2'
    },
    {
        name:'Dart',
        value:'6'
    },
    {
        name:'Assembly',
        value:'5.4'
    },
    {
        name:'Ruby',
        value:'5.2'
    },
    {
        name:'Swift',
        value:'4.7'
    },
    {
        name:'R',
        value:'4.3'
    },
    {
        name:'Visual Basic',
        value:'4.2'
    },
    {
        name:'MATLAB',
        value:'4'
    },
    {
        name:'VBA',
        value:'3.7'
    },
    {
        name:'Groovy',
        value:'3.3'
    },
    {
        name:'Scala',
        value:'2.6'
    },
    {
        name:'Perl',
        value:'2.5'
    },
    {
        name:'GDScript',
        value:'2.3'
    },
    {
        name:'Objective-C',
        value:'2.1'
    },
    {
        name:'Elixir',
        value:'2.1'
    },
    {
        name:'Haskell',
        value:'2'
    },
    {
        name:'Delphi',
        value:'1.8'
    },
    {
        name:'MicroPython',
        value:'1.6'
    },
    {
        name:'Lisp',
        value:'1.5'
    },
    {
        name:'Clojure',
        value:'1.2'
    },
    {
        name:'Julia',
        value:'1.1'
    },
    {
        name:'Zig',
        value:'1.1'
    },
    {
        name:'Fortran',
        value:'1.1'
    },
    {
        name:'Solidity',
        value:'1.1'
    },
    {
        name:'Ada',
        value:'0.9'
    },
    {
        name:'Erlang',
        value:'0.9'
    },
    {
        name:'F#',
        value:'0.9'
    },
    {
        name:'Apex',
        value:'0.8'
    },
    {
        name:'Prolog',
        value:'0.8'
    },
    {
        name:'OCaml',
        value:'0.8'
    },
    {
        name:'Cobol',
        value:'0.7'
    },
    {
        name:'Crystal',
        value:'0.4'
    },
    {
        name:'Nim',
        value:'0.4'
    },
    {
        name:'Zephyr',
        value:'0.3'
    }
]