import { DatosPost, EstilosPost, RefImg } from "@models/categorias.model"

export const ESTILO_ANGULAR: EstilosPost = {
    color: 'c-Angular',
    colorFondo: 'bg-Angular'
}

export const ANGULAR: DatosPost[] = [
    {
        id: 'eb4011f5-81df-4261-b5c5-8f58d2ba88b5',
        nombre: 'ANGULAR.angular.nombre',
        referenciaBusqueda:'ANGULAR.angular.referenciaBusqueda',
        descripcion: ['ANGULAR.angular.descripcion.tx1','ANGULAR.angular.descripcion.tx2','ANGULAR.angular.descripcion.tx3','ANGULAR.angular.descripcion.tx4','ANGULAR.angular.descripcion.tx5'],
        descripcionCorta: 'ANGULAR.angular.descripcionCorta',
        ruta: 'angular',
        componente: 'AngularComponent',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2021-08-02',
        fechaActualizacion: '2021-08-02',
        imgHorizontal:new RefImg(),
        imgVertical:'',
        imgCuadro:'',
        categoria: 'angular',
        posicion: 'rot-1',
        estado: 'inactivo'
    },
    {
        id: '8618eb718b-655b-49a8-9e6e-f3732922b2df',
        nombre: 'ANGULAR.ng-instalacion.nombre',
        referenciaBusqueda:'ANGULAR.ng-instalacion.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-instalacion.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-instalacion.descripcionCorta',
        ruta: 'ng-instalacion',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-03-22',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-horizontal.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-3',
        estado: 'activo',
        imgSlider: {
            alt: 'Instalación Angular y recomendados',
            height: '600',
            id: '2',
            ruta: 'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-SLIDER.jpg',
            width: 'auto',
            post: 'ng-instalacion'
        }
    },
    {
        id: 'ca5b7f7a-af2e-47ce-a69e-4ccf6ec2a317',
        nombre: 'ANGULAR.ng-elementos.nombre',
        referenciaBusqueda:'ANGULAR.ng-elementos.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-elementos.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-elementos.descripcionCorta',
        ruta: 'ng-descripcion-elementos',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/elementos.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'post-z',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: '4f414314-8a56-402c-83dc-807b2af9be53',
        nombre: 'ANGULAR.ng-comunicacion-componentes.nombre',
        referenciaBusqueda:'ANGULAR.ng-comunicacion-componentes.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-comunicacion-componentes.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-comunicacion-componentes.descripcionCorta',
        ruta: 'ng-comunicacion-componentes',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/comunicacion_componentes.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-2',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: 'f3d97128-9f99-42e9-b800-cb1425d016cf',
        nombre: "ANGULAR.ng-arquitectura.nombre",
        referenciaBusqueda:'ANGULAR.ng-arquitectura.referenciaBusqueda',
        descripcion: [
            'ANGULAR.ng-arquitectura.descripcion.tx1',
            'ANGULAR.ng-arquitectura.descripcion.tx2'
        ],
        descripcionCorta: 'ANGULAR.ng-arquitectura.descripcionCorta',
        ruta: 'ng-arquitecturas',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/arquitecturas.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'post-z',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: '7c754f86-a78e-43e3-a6c4-1bad9041c1fa',
        nombre: 'ANGULAR.ng-manejo-rutas.nombre',
        referenciaBusqueda:'ANGULAR.ng-manejo-rutas.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-manejo-rutas.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-manejo-rutas.descripcionCorta',
        ruta: 'ng-manejo-rutas',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/rutas.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'post-z',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: 'fb64a27a-b6ef-44ea-87e5-ff24d6618bbb',
        nombre: 'ANGULAR.ng-microservicios.nombre',
        referenciaBusqueda:'ANGULAR.ng-microservicios.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-microservicios.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-microservicios.descripcionCorta',
        ruta: 'ng-microservicios',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/microservicios.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-2',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: '3d909134-4cf9-4528-a4e3-1a2781d7e6e1',
        nombre: 'ANGULAR.ng-modulos.nombre',
        referenciaBusqueda:'ANGULAR.ng-modulos.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-modulos.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-modulos.descripcionCorta',
        ruta: 'ng-modulos',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/modulos.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-3',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: 'e8512f85-9249-40f0-91d4-1ff9f13db4f0',
        nombre: 'ANGULAR.ng-pruebas-unitarias.nombre',
        referenciaBusqueda:'ANGULAR.ng-pruebas-unitarias.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-pruebas-unitarias.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-pruebas-unitarias.descripcionCorta',
        ruta: 'ng-pruebas-unitarias',
        componente: '',
        mostrarEnPostHome: false,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2023-03-17',
        fechaActualizacion: '2023-09-14',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/unitarias.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-1',
        estado: 'inactivo',
        imgSlider: undefined
    },
    {
        id: '306dc20e-eee2-43de-8f2a-c69f0acd9f82',
        nombre: 'ANGULAR.ng-gh-pages.nombre',
        referenciaBusqueda:'ANGULAR.ng-gh-pages.referenciaBusqueda',
        descripcion: ['ANGULAR.ng-gh-pages.descripcion.tx1'],
        descripcionCorta: 'ANGULAR.ng-gh-pages.descripcionCorta',
        ruta: 'ng-gh-pages',
        componente: '',
        mostrarEnPostHome: true,
        estilos: ESTILO_ANGULAR,
        fechaCreacion: '2024-05-01',
        fechaActualizacion: '2024-05-05',
        imgHorizontal: new RefImg('https://plantillas_dev.gitlab.io/assets/img/posts/angular/githubpages.jpg'),
        imgVertical:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        imgCuadro:'https://plantillas_dev.gitlab.io/assets/img/posts/angular/instalacion-angular-cuadro.jpg',
        categoria: 'angular',
        posicion: 'rot-1',
        estado: 'activo',
        imgSlider: {
            alt: 'Subir proyecto angular a GithubPages',
            height: '600',
            id: '2',
            ruta: 'https://plantillas_dev.gitlab.io/assets/img/posts/angular/slider-ghpages.jpg',
            width: 'auto',
            post: 'ng-gh-pages'
        }
    },
]